---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: '11.16.4'

platforms:
- name: centos6
  driver_config:
    customize:
      memory: 1024
    box: bento/centos-6.9
    hostname: wkhtmltopdf-centos-6
- name: centos7
  driver_config:
    customize:
      memory: 1024
    box: bento/centos-7.3
    hostname: wkhtmltopdf-centos-7
- name: debian9
  driver_config:
    customize:
      memory: 1024
    box: bento/debian-9.0
    hostname: wkhtmltopdf-debian-9
- name: fedora24
  driver_config:
    customize:
      memory: 1024
    box: bento/fedora-24
    hostname: wkhtmltopdf-fedora-24
- name: fedora25
  driver_config:
    customize:
      memory: 1024
    box: bento/fedora-25
    hostname: wkhtmltopdf-fedora-25
- name: freebsd10
  driver_config:
    customize:
      memory: 1024
    box: bento/freebsd-10.3
    hostname: wkhtmltopdf-freebsd-10
- name: freebsd11
  driver_config:
    customize:
      memory: 1024
    box: bento/freebsd-11.0
    hostname: wkhtmltopdf-freebsd-11
- name: ubuntu1204
  driver_config:
    customize:
      memory: 1024
    box: bento/ubuntu-12.04
    hostname: wkhtmltopdf-ubuntu-1204
- name: ubuntu1404
  driver_config:
    customize:
      memory: 1024
    box: bento/ubuntu-14.04
    hostname: wkhtmltopdf-ubuntu-1404

suites:
- name: default
  run_list: ["recipe[wkhtmltopdf]"]
  attributes:
    wkhtmltopdf:
      lib_dir: /usr/local/lib
- name: source
  run_list: ["recipe[wkhtmltopdf]"]
  attributes:
    wkhtmltopdf:
      install_method: source
      lib_dir: /usr/local/lib
      build_cache_path: /var/cache/chef/wkhtmltopdf
